name: Build and Deploy Scorecard

on:
  push:
    branches:
      - main
      - workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore scorecard.sln

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Scorecard project only
        run: msbuild scorecard\scorecard.csproj /p:Configuration=Debug

      - name: Copy build output
        shell: cmd
        run: |
          mkdir deploy
          xcopy scorecard\bin\Debug\* deploy\ /E /I /Y
          if exist scorecard\version.txt copy scorecard\version.txt deploy\

      - name: Push deploy folder to deploy branch
        shell: cmd
        run: |
          cd deploy
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy latest build"
          git branch -M deploy
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push --force origin deploy
